/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class VentanaBanco extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBanco
     */
    public VentanaBanco() {
        initComponents();
    }
    private javax.swing.JLabel lblusuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel ContraUusario;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JButton VerUsuarios;
    private javax.swing.JButton btnAgregar;

    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JLabel lblapellidomaterno;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel lblRFC,lblCURP;
    javax.swing.JTextField txtRFC,txtCURP;
    
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJoshBank = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lblJoshBank.setFont(new java.awt.Font("Arial Nova", 0, 36)); // NOI18N
        lblJoshBank.setText("Josh Bank");

        btnMenu.setBackground(new java.awt.Color(153, 153, 255));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 153, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnMenu)
                .addGap(49, 49, 49)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(lblJoshBank)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoshBank)
                    .addComponent(btnMenu)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnUsuario)
                        .addGap(58, 58, 58)
                        .addComponent(btnAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea salir", "exit window", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Hasta luego c:");
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
        lblusuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        ContraUusario = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
       
        btnUsuario.setVisible(false);
        btnUsuario.setEnabled(false);
        btnAdmin.setVisible(false);
        btnAdmin.setEnabled(false);
        
        lblusuario.setText("Ingrese numero de cuenta");
        getContentPane().add(lblusuario);
        lblusuario.setBounds(60, 120, 200,  200);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(60, 240, 120, 26);
        
        ContraUusario.setText("ingrese contraseña de la cuenta");
        getContentPane().add(ContraUusario);
        ContraUusario.setBounds(60, 180, 200, 200);
        getContentPane().add(Contraseña);
        Contraseña.setBounds(60, 300, 120, 26);
        
        
        
        
        
        
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        
        btnUsuario.setVisible(true);
        btnUsuario.setEnabled(true);
        btnAdmin.setVisible(true);
        btnAdmin.setEnabled(true);
        
        lblusuario.setVisible(false);
        txtUsuario.setVisible(false);
        txtUsuario.setText("");
        
        ContraUusario.setVisible(false);
        Contraseña.setVisible(false);
        Contraseña.setText("");
        
       
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        //agregar botones de ver usuarios, agregar usuarios
        AgregarUsuario = new javax.swing.JButton();
        VerUsuarios = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        btnUsuario.setVisible(false);
        btnUsuario.setEnabled(false);
        btnAdmin.setVisible(false);
        btnAdmin.setEnabled(false);

        AgregarUsuario.setText("Agregar Usuario");
        getContentPane().add(AgregarUsuario);
        AgregarUsuario.setBounds(60, 120, 200,  23);

        VerUsuarios.setText("Ver Usuarios");
        getContentPane().add(VerUsuarios);
        VerUsuarios.setBounds(60, 180, 200, 23);

        //action listener para agregar usuario
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });

        
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        // TODO add your handling code here:

        lblnombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblapellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblapellidomaterno = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        lbldireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblcorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblRFC = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        lblCURP = new javax.swing.JLabel();
        txtCURP = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        btnUsuario.setVisible(false);
        btnUsuario.setEnabled(false);
        btnAdmin.setVisible(false);
        btnAdmin.setEnabled(false);

        AgregarUsuario.setVisible(false);
        AgregarUsuario.setEnabled(false);
        VerUsuarios.setVisible(false);
        VerUsuarios.setEnabled(false);

        lblnombre.setText("Nombre");
        getContentPane().add(lblnombre);
        lblnombre.setBounds(60, 120, 200,  200);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(60, 240, 120, 26);

        lblapellido.setText("Apellido Paterno");
        getContentPane().add(lblapellido);
        lblapellido.setBounds(60, 180, 200, 200);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(60, 300, 120, 26);

        lblapellidomaterno.setText("Apellido Materno");
        getContentPane().add(lblapellidomaterno);
        lblapellidomaterno.setBounds(60, 240, 200, 200);
        getContentPane().add(txtApellidoMaterno);
        txtApellidoMaterno.setBounds(60, 360, 120, 26);

        lblfecha.setText("Fecha de nacimiento");
        getContentPane().add(lblfecha);
        lblfecha.setBounds(60, 300, 200, 200);
        getContentPane().add(txtfecha);
        txtfecha.setBounds(60, 420, 120, 26);

        lbldireccion.setText("Direccion");
        getContentPane().add(lbldireccion);
        lbldireccion.setBounds(60, 360, 200, 200);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(60, 480, 120, 26);

        //los siguientes en del lado derecho de la ventana
        lbltelefono.setText("Telefono");
        getContentPane().add(lbltelefono);
        lbltelefono.setBounds(300, 120, 200,  200);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(300, 240, 120, 26);

        lblcorreo.setText("Correo");
        getContentPane().add(lblcorreo);
        lblcorreo.setBounds(300, 180, 200, 200);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(300, 300, 120, 26);

        lblRFC.setText("RFC");
        getContentPane().add(lblRFC);
        lblRFC.setBounds(300, 240, 200, 200);
        getContentPane().add(txtRFC);
        txtRFC.setBounds(300, 360, 120, 26);

        lblCURP.setText("CURP");
        getContentPane().add(lblCURP);
        lblCURP.setBounds(300, 300, 200, 200);
        getContentPane().add(txtCURP);
        txtCURP.setBounds(300, 420, 120, 26);

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(300, 480, 120, 23);

        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });


    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    //action listener para agregar usuario donde solo se guarden en variables locales
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre,apellido,apellidomaterno,fecha,direccion,telefono,correo,RFC,CURP;
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        apellidomaterno = txtApellidoMaterno.getText();
        fecha = txtfecha.getText();
        direccion = txtDireccion.getText();
        telefono = txtTelefono.getText();
        correo = txtCorreo.getText();
        RFC = txtRFC.getText();
        CURP = txtCURP.getText();

        //aqui se limpian los campos
        txtNombre.setText("");
        txtApellido.setText("");
        txtApellidoMaterno.setText("");
        txtfecha.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtRFC.setText("");
        txtCURP.setText("");

        //aqui se regresa a la ventana anterior
        btnUsuario.setVisible(false);
        btnUsuario.setEnabled(false);
        btnAdmin.setVisible(false);
        btnAdmin.setEnabled(false);

        AgregarUsuario.setVisible(true);
        AgregarUsuario.setEnabled(true);
        VerUsuarios.setVisible(true);
        VerUsuarios.setEnabled(true);

        lblnombre.setVisible(false);
        txtNombre.setVisible(false);
        txtNombre.setText("");

        lblapellido.setVisible(false);
        txtApellido.setVisible(false);
        txtApellido.setText("");

        lblapellidomaterno.setVisible(false);
        txtApellidoMaterno.setVisible(false);
        txtApellidoMaterno.setText("");

        lblfecha.setVisible(false);
        txtfecha.setVisible(false);
        txtfecha.setText("");

        lbldireccion.setVisible(false);
        txtDireccion.setVisible(false);
        txtDireccion.setText("");

        lbltelefono.setVisible(false);
        txtTelefono.setVisible(false);
        txtTelefono.setText("");

        lblcorreo.setVisible(false);
        txtCorreo.setVisible(false);
        txtCorreo.setText("");

        lblRFC.setVisible(false);
        txtRFC.setVisible(false);
        txtRFC.setText("");

        lblCURP.setVisible(false);
        txtCURP.setVisible(false);
        txtCURP.setText("");

        btnAgregar.setVisible(false);
        btnAgregar.setEnabled(false);
    }//GEN-LAST:event_btnAgregarActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJoshBank;
    // End of variables declaration//GEN-END:variables
}
